[tools]
go                = "1.25"
golangci-lint     = "2.7.2"
"ubi:matryer/moq" = "0.6.0"

[tasks.fmt]
run = "golangci-lint fmt"

[tasks.gen]
run = "go generate -x ./..."

[tasks.lint]
depends = ["gen"]
run = "golangci-lint run ./..."

[tasks.test]
depends = ["gen"]
run = "go test -race ./..."
